apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: devops-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: jester91/devops-challenge:latest
        ports:
        - containerPort: 8000
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: SECRET_KEY
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
        command: ["sh", "-c", "cd polls/ && python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py loaddata fixtures/initial_data.json && uwsgi --ini uwsgi.ini"]
        volumeMounts:
        - name: code
          mountPath: /code
        - name: static-volume
          mountPath: /code/static
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: code
        persistentVolumeClaim:
          claimName: web-pvc
      - name: static-volume
        persistentVolumeClaim:
          claimName: static-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc
  namespace: devops-challenge
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
  namespace: devops-challenge
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: devops-challenge
spec:
  selector:
    app: web
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer
