name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      working-directory: infra
      run: terraform init

    - name: Terraform fmt
      working-directory: infra
      run: terraform fmt      

    - name: Terraform Apply
      working-directory: infra
      run: terraform apply -auto-approve

    - name: Set up Azure CLI
      uses: azure/setup-azure-cli@v2

    - name: Azure Login
      run: az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Get AKS Credentials
      run: az aks get-credentials --resource-group devops-challenge-rg --name devops-challenge-aks

    - name: Deploy to AKS
      run: |
        kubectl apply -f devops-challenge/deployment/namespace.yaml
        kubectl apply -f devops-challenge/deployment/secret.yaml
        kubectl apply -f devops-challenge/deployment/db.yaml
        kubectl apply -f devops-challenge/deployment/deployment.yaml
